/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.3-rc-2/userguide/building_swift_projects.html in the Gradle documentation.
 */

pluginManagement {
    val REPOS_SERVER: String by settings

    repositories {
        maven {
            url = uri("${REPOS_SERVER}/google")
            isAllowInsecureProtocol = true
        }

        maven {
            url = uri("${REPOS_SERVER}/central")
            isAllowInsecureProtocol = true
        }

        maven {
            url = uri("${REPOS_SERVER}/gradle-plugin")
            isAllowInsecureProtocol = true
        }
    }
}

dependencyResolutionManagement {
    val REPOS_SERVER: String by settings

    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            url = uri("${REPOS_SERVER}/google")
            isAllowInsecureProtocol = true
        }

        maven {
            url = uri("${REPOS_SERVER}/central")
            isAllowInsecureProtocol = true
        }

        maven {
            url = uri("${REPOS_SERVER}/jitpack")
            isAllowInsecureProtocol = true
        }
    }
}

rootProject.name = "SimbokSDKDemo"
include("app", "libIrisHelper")