/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    application
    java
//    id("org.javamodularity.moduleplugin") version ("1.8.12")
//    id("org.openjfx.javafxplugin") version ("0.0.14")
//    id("org.beryx.jlink") version ("2.25.0")
}

dependencies {
    implementation(project(":libIrisHelper"))

//    val jfx = "21.0.5"
//    implementation("org.openjfx:javafx:$jfx")
//    implementation("org.openjfx:controls:$jfx")
//    implementation("org.openjfx:fxml:$jfx")
}

group = "cn.simbok"
version = "1.0"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

//javafx {
//    version = "17.0.6"
//    modules = arrayListOf(
//        "javafx.controls",
//        "javafx.fxml"
//    )
//}

//jlink {
//    imageZip.set(file("${buildDir}/distributions/app-${javafx.platform.classifier}.zip"))
//    options = arrayListOf(
//        "--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"
//    )
//    launcher { name = "app" }
//}

application {
    mainModule.set("cn.simbok.demo")
    mainClass.set("cn.simbok.demo.App")

    // 配置JNI库路径
    val jniPath = "F:/iris_java/Windows SDK_3.23.6_x64_Eng/win_pidsdk_3.23.6_x64/bin"
    applicationDefaultJvmArgs = arrayListOf(
        "-Djava.library.path=$jniPath"
    )
}


tasks.withType(JavaCompile::class.java) {
    options.encoding = "UTF-8"
}